/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehouseListRouteImport } from './routes/_authenticated/warehouse-list'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedStockTransferRouteImport } from './routes/_authenticated/stock-transfer'
import { Route as AuthenticatedStockAdjustmentRouteImport } from './routes/_authenticated/stock-adjustment'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedLowStockAlertsRouteImport } from './routes/_authenticated/low-stock-alerts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedModuleSlugRouteImport } from './routes/_authenticated/module.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehouseListRoute =
  AuthenticatedWarehouseListRouteImport.update({
    id: '/warehouse-list',
    path: '/warehouse-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockTransferRoute =
  AuthenticatedStockTransferRouteImport.update({
    id: '/stock-transfer',
    path: '/stock-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockAdjustmentRoute =
  AuthenticatedStockAdjustmentRouteImport.update({
    id: '/stock-adjustment',
    path: '/stock-adjustment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLowStockAlertsRoute =
  AuthenticatedLowStockAlertsRouteImport.update({
    id: '/low-stock-alerts',
    path: '/low-stock-alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModuleSlugRoute = AuthenticatedModuleSlugRouteImport.update({
  id: '/module/$slug',
  path: '/module/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/low-stock-alerts': typeof AuthenticatedLowStockAlertsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/stock-adjustment': typeof AuthenticatedStockAdjustmentRoute
  '/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/warehouse-list': typeof AuthenticatedWarehouseListRoute
  '/module/$slug': typeof AuthenticatedModuleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/low-stock-alerts': typeof AuthenticatedLowStockAlertsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/stock-adjustment': typeof AuthenticatedStockAdjustmentRoute
  '/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/warehouse-list': typeof AuthenticatedWarehouseListRoute
  '/module/$slug': typeof AuthenticatedModuleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/low-stock-alerts': typeof AuthenticatedLowStockAlertsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/stock-adjustment': typeof AuthenticatedStockAdjustmentRoute
  '/_authenticated/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/warehouse-list': typeof AuthenticatedWarehouseListRoute
  '/_authenticated/module/$slug': typeof AuthenticatedModuleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/dashboard'
    | '/low-stock-alerts'
    | '/products'
    | '/stock-adjustment'
    | '/stock-transfer'
    | '/units'
    | '/warehouse-list'
    | '/module/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/dashboard'
    | '/low-stock-alerts'
    | '/products'
    | '/stock-adjustment'
    | '/stock-transfer'
    | '/units'
    | '/warehouse-list'
    | '/module/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/brands'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/low-stock-alerts'
    | '/_authenticated/products'
    | '/_authenticated/stock-adjustment'
    | '/_authenticated/stock-transfer'
    | '/_authenticated/units'
    | '/_authenticated/warehouse-list'
    | '/_authenticated/module/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouse-list': {
      id: '/_authenticated/warehouse-list'
      path: '/warehouse-list'
      fullPath: '/warehouse-list'
      preLoaderRoute: typeof AuthenticatedWarehouseListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-transfer': {
      id: '/_authenticated/stock-transfer'
      path: '/stock-transfer'
      fullPath: '/stock-transfer'
      preLoaderRoute: typeof AuthenticatedStockTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-adjustment': {
      id: '/_authenticated/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof AuthenticatedStockAdjustmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/low-stock-alerts': {
      id: '/_authenticated/low-stock-alerts'
      path: '/low-stock-alerts'
      fullPath: '/low-stock-alerts'
      preLoaderRoute: typeof AuthenticatedLowStockAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/module/$slug': {
      id: '/_authenticated/module/$slug'
      path: '/module/$slug'
      fullPath: '/module/$slug'
      preLoaderRoute: typeof AuthenticatedModuleSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLowStockAlertsRoute: typeof AuthenticatedLowStockAlertsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedStockAdjustmentRoute: typeof AuthenticatedStockAdjustmentRoute
  AuthenticatedStockTransferRoute: typeof AuthenticatedStockTransferRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedWarehouseListRoute: typeof AuthenticatedWarehouseListRoute
  AuthenticatedModuleSlugRoute: typeof AuthenticatedModuleSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLowStockAlertsRoute: AuthenticatedLowStockAlertsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedStockAdjustmentRoute: AuthenticatedStockAdjustmentRoute,
  AuthenticatedStockTransferRoute: AuthenticatedStockTransferRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedWarehouseListRoute: AuthenticatedWarehouseListRoute,
  AuthenticatedModuleSlugRoute: AuthenticatedModuleSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
